# Generated by Django 3.1.12 on 2024-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0002_auto_20240513_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
